### ISSUE TITLE
能否将镜像合并一下

### ISSUE THREAD

**Issue by gtahoo** [TuGraph-family/OSGraph#52]
参考开发手册走下来，需要拉3个镜像（TuGraph-DB一个、ES一个、MySQl一个），能否将镜像都合并一下？

**Comment by fanzhidongyzby** [comment]
> 参考开发手册走下来，需要拉3个镜像（TuGraph-DB一个、ES一个、MySQl一个），能否将镜像都合并一下？

建议支持本地化部署合并为一个镜像。或者使用docker compose方案。
